services:
  jekyll:
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    command: >
      bash -c "
        bundle install &&
        bundle exec jekyll serve --host 0.0.0.0 --port 8080 --livereload --livereload-port 35729 --force_polling --incremental
      "
    
volumes:
  bundle_cache: